// Comprehensive type definitions for the Media Summarizer plugin
// Eliminates 'any' types and provides proper type safety

import { Editor, MarkdownView } from 'obsidian';

// Base interfaces
export interface VideoMetadata {
    id: string;
    title?: string;
    description?: string;
    duration?: number;
    thumbnailUrl?: string;
    channelName?: string;
    publishedAt?: string;
}

export interface TranscriptLine {
    text: string;
    start: number;
    duration: number;
    end?: number;
}

export interface TranscriptData {
    lines: TranscriptLine[];
    language?: string;
    isAutoGenerated?: boolean;
    source: 'youtube' | 'external' | 'api';
    videoId: string;
    metadata?: VideoMetadata;
}

// Provider-related interfaces
export interface ProviderCredentials {
    apiKey: string;
    model: string;
    customModel?: string;
    temperature?: number;
    baseUrl?: string;
}

export interface OpenAICredentials extends ProviderCredentials {
    customModel?: string;
    temperature?: number;
}

export interface OpenRouterCredentials extends ProviderCredentials {
    customModel?: string;
    temperature?: number;
}

export interface OllamaCredentials {
    baseUrl: string;
    model: string;
    customModel?: string;
    temperature?: number;
}

export interface ProviderSettings {
    openai: OpenAICredentials;
    openrouter: OpenRouterCredentials;
    ollama: OllamaCredentials;
}

// API Response interfaces
export interface OpenAIModel {
    id: string;
    object: string;
    created: number;
    owned_by: string;
    permission?: any[];
    root?: string;
    parent?: string;
}

export interface OpenAIModelsResponse {
    object: string;
    data: OpenAIModel[];
}

export interface OpenRouterModel {
    id: string;
    name: string;
    description?: string;
    pricing: {
        prompt: string;
        completion: string;
    };
    context_length: number;
    architecture: {
        modality: string;
        tokenizer: string;
        instruct_type?: string;
    };
    top_provider: {
        context_length: number;
        max_completion_tokens?: number;
    };
}

export interface OpenRouterModelsResponse {
    data: OpenRouterModel[];
}

export interface OllamaModel {
    name: string;
    modified_at: string;
    size: number;
    digest: string;
    details: {
        format: string;
        family: string;
        families?: string[];
        parameter_size: string;
        quantization_level: string;
    };
}

export interface OllamaModelsResponse {
    models: OllamaModel[];
}

// YouTube API interfaces
export interface YouTubeVideoDetails {
    id: string;
    snippet: {
        title: string;
        description: string;
        channelTitle: string;
        publishedAt: string;
        thumbnails: {
            default: { url: string; width: number; height: number };
            medium: { url: string; width: number; height: number };
            high: { url: string; width: number; height: number };
        };
    };
    contentDetails: {
        duration: string;
    };
}

export interface YouTubeCaptionTrack {
    kind: string;
    etag: string;
    id: string;
    snippet: {
        videoId: string;
        lastUpdated: string;
        trackKind: string;
        language: string;
        name: string;
        audioTrackType: string;
        isCC: boolean;
        isLarge: boolean;
        isEasyReader: boolean;
        isDraft: boolean;
        isAutoSynced: boolean;
        status: string;
    };
}

// Command interfaces
export interface CommandContext {
    editor: Editor;
    view: MarkdownView;
}

export interface VideoPlayerCommand {
    execute(context: CommandContext): Promise<boolean>;
    canExecute(context: CommandContext): boolean;
}

// Settings interfaces
export interface PlaybackSettings {
    defaultSpeed: number;
    seekSeconds: number;
    timestampOffsetSeconds: number;
    playbackOffsetSeconds: number;
    pauseOnTimestampInsert: boolean;
}

export interface TranscriptSettings {
    enableEnhancedTranscript: boolean;
    enableExternalTranscriptDetection: boolean;
    externalTranscriptProvider: string;
    externalTranscriptProviderModel: string;
    checkExternalTranscripts: boolean;
}

export interface AISettings {
    enableSummarization: boolean;
    currentProvider: 'openai' | 'openrouter' | 'ollama';
    providers: ProviderSettings;
}

export interface ExternalAPISettings {
    youtubeApiKey?: string;
    webScrapingApiKey?: string;
}

// Processing interfaces
export interface ProcessingOptions {
    enhanceFormatting?: boolean;
    includeTimestamps?: boolean;
    chunkForLongContent?: boolean;
    maxChunkSize?: number;
}

export interface ProcessingResult<T> {
    success: boolean;
    data?: T;
    error?: string;
    metadata?: Record<string, any>;
}

export interface TranscriptProcessingResult extends ProcessingResult<string> {
    originalLength?: number;
    processedLength?: number;
    enhancementsApplied?: string[];
    chunked?: boolean;
    chunkCount?: number;
}

export interface SummarizationResult extends ProcessingResult<string> {
    tokensUsed?: number;
    provider?: string;
    model?: string;
    processingTimeMs?: number;
}

// Event interfaces
export interface PluginEvent {
    type: string;
    timestamp: Date;
    source: string;
    data?: Record<string, any>;
}

export interface VideoPlayerEvent extends PluginEvent {
    videoId?: string;
    currentTime?: number;
    action: 'play' | 'pause' | 'seek' | 'speed_change' | 'mute' | 'unmute';
}

export interface TranscriptEvent extends PluginEvent {
    videoId: string;
    action: 'fetch_start' | 'fetch_success' | 'fetch_error' | 'enhance_start' | 'enhance_success' | 'enhance_error';
    source?: 'youtube' | 'external' | 'api';
}

// UI Component interfaces
export interface ButtonConfig {
    id: string;
    label: string;
    icon?: string;
    tooltip?: string;
    enabled: boolean;
    onClick: () => Promise<void> | void;
}

export interface DropdownConfig {
    id: string;
    label: string;
    options: Array<{ value: string; label: string; disabled?: boolean }>;
    value: string;
    onChange: (value: string) => Promise<void> | void;
}

export interface SliderConfig {
    id: string;
    label: string;
    min: number;
    max: number;
    step: number;
    value: number;
    onChange: (value: number) => Promise<void> | void;
}

// Validation interfaces
export interface ValidationRule<T> {
    validate(value: T): boolean;
    errorMessage: string;
}

export interface ValidationResult {
    isValid: boolean;
    errors: string[];
    warnings?: string[];
}

export interface APIKeyValidation extends ValidationResult {
    format: 'valid' | 'invalid' | 'unknown';
    provider?: string;
}

// Error interfaces
export interface ErrorInfo {
    code: string;
    message: string;
    details?: Record<string, any>;
    timestamp: Date;
    recoverable: boolean;
}

export interface APIError extends ErrorInfo {
    httpStatus?: number;
    provider: string;
    endpoint?: string;
    retryable: boolean;
}

// Utility type helpers
export type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends object ? DeepPartial<T[P]> : T[P];
};

export type RequiredFields<T, K extends keyof T> = T & Required<Pick<T, K>>;

export type ProviderType = 'openai' | 'openrouter' | 'ollama';

export type TranscriptSource = 'youtube' | 'external' | 'api';

export type PlaybackSpeed = 0.5 | 0.75 | 1 | 1.25 | 1.5 | 2;

export type VideoPlayerState = 'unstarted' | 'ended' | 'playing' | 'paused' | 'buffering' | 'cued';

// Functional interfaces
export interface Disposable {
    dispose(): void;
}

export interface Refreshable {
    refresh(): Promise<void>;
}

export interface Configurable<T> {
    configure(config: T): void;
    getConfiguration(): T;
}

// Factory interfaces
export interface ServiceFactory<T> {
    create(): T;
    getInstance(): T;
}

export interface ProviderFactory {
    createProvider(type: ProviderType, credentials: ProviderCredentials): any;
    validateCredentials(type: ProviderType, credentials: ProviderCredentials): ValidationResult;
}

// Cache interfaces
export interface CacheEntry<T> {
    value: T;
    timestamp: Date;
    ttl: number;
}

export interface Cache<T> {
    get(key: string): T | null;
    set(key: string, value: T, ttl?: number): void;
    delete(key: string): boolean;
    clear(): void;
    size(): number;
}

// Migration interfaces
export interface MigrationTask {
    version: string;
    description: string;
    migrate(settings: any): any;
    rollback?(settings: any): any;
}

export interface MigrationResult {
    success: boolean;
    fromVersion: string;
    toVersion: string;
    tasksExecuted: string[];
    errors?: string[];
}

// Plugin lifecycle interfaces
export interface PluginLifecycle {
    onLoad(): Promise<void>;
    onUnload(): void;
    onSettingsChange?(settings: any): Promise<void>;
    onConfigurationChange?(config: any): Promise<void>;
}

// Analytics interfaces (for future use)
export interface AnalyticsEvent {
    name: string;
    properties: Record<string, any>;
    timestamp: Date;
    userId?: string;
    sessionId?: string;
}

export interface AnalyticsProvider {
    track(event: AnalyticsEvent): void;
    identify(userId: string, traits?: Record<string, any>): void;
    flush(): Promise<void>;
}